tickers:
  # Australian Equities
  - VAS.AX
  - VHY.AX
  - IOZ.AX
  # Global Equities
  - VGS.AX
  - VGAD.AX
  - IVV.AX
  # Fixed Income
  - VAF.AX
  - IAF.AX
  - VACF.AX
  # Defensive / Real Return
  - GROW.AX
  - VDBA.AX
  - DHHF.AX
  # Property & Infrastructure
  - VAP.AX
  - IFRA.AX
