tickers:
  # Australian Equities
  - VAS.AX
  - IOZ.AX
  - VHY.AX
  # International Developed Equities
  - VGS.AX
  - VGAD.AX
  - IVV.AX
  - VEU.AX
  - BGBL.AX
  # International Small Caps
  - VISM.AX
  - IJR.AX
  # Emerging Markets
  - VGE.AX
  - IEM.AX
  # Property
  - VAP.AX
  # Infrastructure
  - IFRA.AX
  - GLIN.AX
  # Australian Bonds
  - VAF.AX
  - IAF.AX
  # Credit
  - VACF.AX
  - QPON.AX
  - FLOT.AX
  - MXT.AX
  - MOT.AX
  - PCI.AX
  # Inflation Protection
  - ILB.AX
  # Diversified / Real Return
  - GROW.AX
  - VDBA.AX
  - DHHF.AX
  # Alternatives
  - GOLD.AX
